routes/user.php
<?php

use Illuminate\Support\Facades\Route;

use App\Http\Controllers\Auth\AuthController;
use App\Http\Controllers\HomeController;

use App\Http\Controllers\Main\Manage\UserController;
use App\Http\Controllers\Main\Manage\SettingController;
use App\Http\Controllers\Main\Manage\AksesMenuController;

use App\Http\Controllers\Main\Setting\SettingHomePageController;
use App\Http\Controllers\Main\Setting\SettingBiayaController;
use App\Http\Controllers\Main\Setting\SettingTentangController;
use App\Http\Controllers\Main\Setting\SettingTestimoniController;

use App\Http\Controllers\MainFront\IndexController;
use App\Http\Controllers\MainFront\BiayaController;
use App\Http\Controllers\MainFront\TentangController;


use App\Http\Controllers\User\UserSettingUmumController;
use App\Http\Controllers\User\UserSocialMediaController;
use App\Http\Controllers\User\UserFooterController;
use App\Http\Controllers\User\UserMenuController;
use App\Http\Controllers\User\UserPageController;
use App\Http\Controllers\User\UserSliderController;
use App\Http\Controllers\User\UserBannerController;


use App\Http\Controllers\UserFront\UserFrontendController;
use App\Http\Controllers\UserFront\UserFrontendMenuController;



/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::group(['middleware' => ['web']], function () {

    /*
    * Routes Untuk Halaman Awal Website Utama
    */

    Route::get('/reload-captcha', [App\Http\Controllers\Auth\RegisterController::class, 'reloadCaptcha'])->name('reloadCaptcha');

    Route::get('/', [IndexController::class, 'index'])->name('homepage.index');

    Route::get('biaya', [BiayaController::class, 'index'])->name('biaya.index');

    Route::get('tentang', [TentangController::class, 'index'])->name('tentang.index');
});


Route::group(['middleware' => ['web']], function () {

    /*
    * Routes Untuk Fitur2 Halaman User
    */
    Route::prefix('web')->group(function () {

        Route::get('{username}', [UserFrontendController::class, 'index']);

        Route::get('{username}/{menuname}', [UserFrontendMenuController::class, 'index']);
    });
});


/*
* Routes Setelah Login
*/
Route::group(['middleware' => ['auth']], function () {
    /*
    * Routes Untuk Fitur2 Dashboard
    */
    Route::get('home', [HomeController::class, 'index'])->name('dashboard.index');

    /*
    * Routes Untuk Fitur2 User
    */
    Route::prefix('user')->group(function () {
        Route::resource('user-setting-umum', UserSettingUmumController::class);

        Route::resource('user-social-media', UserSocialMediaController::class);

        Route::resource('user-footer', UserFooterController::class);

        Route::resource('user-menu', UserMenuController::class);

        Route::resource('user-page', UserPageController::class);

        Route::resource('user-slider', UserSliderController::class);

        Route::resource('user-banner', UserBannerController::class);
    });
});

routes/web.php
<?php

use Illuminate\Support\Facades\Route;

use App\Http\Controllers\Auth\AuthController;
use App\Http\Controllers\Auth\RegisterController;
use App\Http\Controllers\HomeController;

use App\Http\Controllers\Main\Manage\UserController;
use App\Http\Controllers\Main\Manage\SettingController;
use App\Http\Controllers\Main\Manage\AksesMenuController;

use App\Http\Controllers\Main\Setting\SettingHomePageController;
use App\Http\Controllers\Main\Setting\SettingBiayaController;
use App\Http\Controllers\Main\Setting\SettingTentangController;
use App\Http\Controllers\Main\Setting\SettingTestimoniController;

use App\Http\Controllers\MainFront\IndexController;
use App\Http\Controllers\MainFront\BiayaController;
use App\Http\Controllers\MainFront\TentangController;
use App\Http\Controllers\MainFront\WebStoreController;
use App\Http\Controllers\MainFront\TestimoniController;


use App\Http\Controllers\User\UserSettingUmumController;
use App\Http\Controllers\User\UserSocialMediaController;
use App\Http\Controllers\User\UserFooterController;
use App\Http\Controllers\User\UserMenuController;
use App\Http\Controllers\User\UserPageController;
use App\Http\Controllers\User\UserSliderController;
use App\Http\Controllers\User\UserBannerController;
use App\Http\Controllers\User\UserPostController;
use App\Http\Controllers\User\UserTextController;
use App\Http\Controllers\User\UserStoreController;


use App\Http\Controllers\UserFront\UserFrontendController;
use App\Http\Controllers\UserFront\UserFrontendMenuController;



/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::group(['middleware' => ['web', 'visitors']], function () {

    /*
    * Routes Untuk Halaman Awal Website Utama
    */

    Route::get('/reload-captcha', [RegisterController::class, 'reloadCaptcha'])->name('reloadCaptcha');

    Route::get('/', [IndexController::class, 'index'])->name('homepage.index');

    Route::get('biaya', [BiayaController::class, 'index'])->name('biaya.index');

    Route::get('webstore', [WebStoreController::class, 'index'])->name('webstore.index');

    Route::get('tentang', [TentangController::class, 'index'])->name('tentang.index');

    Route::get('testimoni', [TestimoniController::class, 'index'])->name('testimoni.index');
});



/*
* Routes Setelah Login ( ADMIN )
*/
Route::group(['middleware' => ['auth']], function () {
    /*
    * Routes Untuk Fitur2 Dashboard
    */
    Route::get('home', [HomeController::class, 'index'])->name('dashboard.index');

    Route::get('wait', [HomeController::class, 'wait'])->name('wait.index');

    /*
    * Routes Untuk Fitur2 Setting
    */
    Route::prefix('setting')->group(function () {
        /*
        * Routes Untuk Fitur2 User Management
        */
        Route::resource('user', UserController::class);
        Route::get('user/{id}/profil', [UserController::class, 'getProfile'])->name('user.profil');
        Route::patch('user/{id}/profil', [UserController::class, 'updateProfile']);
        Route::post('user/{id}/uploadfoto',  [UserController::class, 'storefotoUpload'])->name('user.uploadfoto');

        Route::post('active-useradmin/{id}', [UserController::class, 'active'])->name('user-admin.active');
    });

    /*
    * Routes Untuk Fitur2 Admin
    */
    Route::prefix('admin')->group(function () {

        Route::resource('setting-homepage', SettingHomePageController::class);
        Route::post('active-homepage/{id}', [SettingHomePageController::class, 'active'])->name('setting-homepage.active');

        Route::resource('setting-biaya', SettingBiayaController::class);
        Route::post('active-biaya/{id}', [SettingBiayaController::class, 'active'])->name('setting-biaya.active');

        Route::resource('setting-tentang', SettingTentangController::class);
        Route::post('active-tentang/{id}', [SettingTentangController::class, 'active'])->name('setting-tentang.active');

        Route::resource('setting-testimoni', SettingTestimoniController::class);
        Route::post('active-testimoni/{id}', [SettingTestimoniController::class, 'active'])->name('setting-testimoni.active');
    });


    /*
    * Routes Untuk Fitur2 User Administration
    */
    Route::prefix('user')->group(function () {
        Route::resource('user-setting-umum', UserSettingUmumController::class);
        Route::post('active-settingumum/{id}', [UserSettingUmumController::class, 'active'])->name('user-settingumum.active');

        Route::resource('user-social-media', UserSocialMediaController::class);
        Route::post('active-socialmedia/{id}', [UserSocialMediaController::class, 'active'])->name('user-socialmedia.active');

        Route::resource('user-footer', UserFooterController::class);
        Route::post('active-userfooter/{id}', [UserFooterController::class, 'active'])->name('user-footer.active');

        Route::resource('user-menu', UserMenuController::class);
        Route::post('active-usermenu/{id}', [UserMenuController::class, 'active'])->name('user-menu.active');

        Route::resource('user-page', UserPageController::class);
        Route::post('active-userpage/{id}', [UserPageController::class, 'active'])->name('user-page.active');


        Route::resource('user-slider', UserSliderController::class);
        Route::post('active-userslider/{id}', [UserSliderController::class, 'active'])->name('user-slider.active');

        Route::resource('user-banner', UserBannerController::class);
        Route::post('active-userbanner/{id}', [UserBannerController::class, 'active'])->name('user-banner.active');

        Route::resource('user-post', UserPostController::class);
        Route::post('active-userpost/{id}', [UserPostController::class, 'active'])->name('user-post.active');

        Route::resource('user-text', UserTextController::class);
        Route::post('active-usertext/{id}', [UserTextController::class, 'active'])->name('user-text.active');


        Route::resource('user-store', UserStoreController::class);
        Route::post('active-userstore/{id}', [UserStoreController::class, 'active'])->name('user-store.active');

        //
    });
});

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Facades\Auth;
use Laravel\Sanctum\HasApiTokens;
use Spatie\Permission\Traits\HasRoles;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable, HasRoles, SoftDeletes;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'username',
        'password',
    ];

    /**
     * The attributes that should be mutated to dates.
     *
     * @var array
     */
    protected $dates = ['deleted_at'];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    protected static function boot()
    {
        parent::boot();

        static::creating(function ($model) {
            $model->created_by = is_object(Auth::guard(config('app.guards.web'))->user()) ? Auth::guard(config('app.guards.web'))->user()->id : 1;
            $model->updated_by = NULL;
        });

        static::updating(function ($model) {
            $model->updated_by = is_object(Auth::guard(config('app.guards.web'))->user()) ? Auth::guard(config('app.guards.web'))->user()->id : 1;
        });

        static::deleting(function ($model) {
            $model->deleted_by = is_object(Auth::guard(config('app.guards.web'))->user()) ? Auth::guard(config('app.guards.web'))->user()->id : 1;

            $model->save();
        });
    }
}

app/Http/Controllers/User/UserPostDetailController.php
<?php

namespace App\Http\Controllers\User;

use App\Http\Controllers\Controller;
use App\Http\Requests;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;
use RealRashid\SweetAlert\Facades\Alert;
use Carbon\Carbon;
use Image;

use App\Models\UserPostDetail;

class UserPostDetailController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\View\View
     */
    public function index(Request $request)
    {
        // if (!auth()->user()->can('userPostDetail.create')) {
        //    abort(403, 'Anda Tidak Diijinkan Mengakses Halaman Ini.');
        // }

        $keyword = $request->get('search');
        $perPage = 25;

        if (!empty($keyword)) {
            $userpostdetail = UserPostDetail::where('username',  env('USERNAME'))
                ->where('user_id', env('USERID'))
                ->orWhere('username', 'LIKE', "%$keyword%")
                ->orWhere('menu_id', 'LIKE', "%$keyword%")
                ->orWhere('page_id', 'LIKE', "%$keyword%")
                ->orWhere('foto', 'LIKE', "%$keyword%")
                ->orWhere('thumbnail', 'LIKE', "%$keyword%")
                ->orWhere('title', 'LIKE', "%$keyword%")
                ->orWhere('detail', 'LIKE', "%$keyword%")
                ->orWhere('link', 'LIKE', "%$keyword%")
                ->orWhere('category', 'LIKE', "%$keyword%")
                ->orWhere('file', 'LIKE', "%$keyword%")
                ->latest()->get($perPage);
        } else {
            $userpostdetail = UserPostDetail::where('username',  env('USERNAME'))
                ->where('user_id', env('USERID'))->get();
        }

        return view('user.user-post-detail.index', compact('userpostdetail'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\View\View
     */
    public function create()
    {
        // if (!auth()->user()->can('userPostDetail.create')) {
        //    abort(403, 'Anda Tidak Diijinkan Mengakses Halaman Ini.');
        // }

        return view('user.user-post-detail.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     *
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     */
    public function store(Request $request)
    {
        $requestData = $request->all();

        UserPostDetail::create($requestData);

        // if (!auth()->user()->can('userPostDetail.create')) {
        //    abort(403, 'Anda Tidak Diijinkan Mengakses Halaman Ini.');
        // }

        $validator = Validator::make($request->all(), [
            '' => 'required|max:255',
            '' => 'required',
            '' => 'required|numeric',
            '' => 'required',
        ]);

        if ($validator->fails()) {
            return redirect()->back()->withErrors($validator)->withInput();
        } else {
            $UserPostDetail = new UserPostDetail();
            $UserPostDetail->UserPostDetail = $request->get('');
            $UserPostDetail->UserPostDetail = $request->get('');
            $UserPostDetail->UserPostDetail = $request->get('');

            $UserPostDetail->save();
        }

        alert()->success('Simpan Data UserPostDetail', 'Sukses')->autoclose(10000);

        return redirect('user-post-detail');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     *
     * @return \Illuminate\View\View
     */
    public function show($id)
    {
        // if (!auth()->user()->can('userPostDetail.show')) {
        //    abort(403, 'Anda Tidak Diijinkan Mengakses Halaman Ini.');
        // }

        $userpostdetail = UserPostDetail::findOrFail($id);

        return view('user.user-post-detail.show', compact('userpostdetail'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     *
     * @return \Illuminate\View\View
     */
    public function edit($id)
    {
        // if (!auth()->user()->can('userPostDetail.edit')) {
        //    abort(403, 'Anda Tidak Diijinkan Mengakses Halaman Ini.');
        // }

        $userpostdetail = UserPostDetail::findOrFail($id);

        return view('user.user-post-detail.edit', compact('userpostdetail'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param  int  $id
     *
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     */
    public function update(Request $request, $id)
    {

        $requestData = $request->all();

        $userpostdetail = UserPostDetail::findOrFail($id);
        $userpostdetail->update($requestData);

        // if (!auth()->user()->can('userPostDetail.edit')) {
        //    abort(403, 'Anda Tidak Diijinkan Mengakses Halaman Ini.');
        // }

        $validator = Validator::make($request->all(), [
            '' => 'required|max:255',
            '' => 'required',
            '' => 'required|numeric',
            '' => 'required',
        ]);

        if ($validator->fails()) {
            return redirect()->back()->withErrors($validator)->withInput();
        } else {
            $UserPostDetail = new UserPostDetail();
            $UserPostDetail->UserPostDetail = $request->get('');
            $UserPostDetail->UserPostDetail = $request->get('');
            $UserPostDetail->UserPostDetail = $request->get('');

            $UserPostDetail->save();
        }

        alert()->success('Update Data UserPostDetail', 'Sukses')->autoclose(10000);

        return redirect('user-post-detail');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     *
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     */
    public function destroy($id)
    {
        // if (!auth()->user()->can('userPostDetail.delete')) {
        //    abort(403, 'Anda Tidak Diijinkan Mengakses Halaman Ini.');
        // }

        UserPostDetail::destroy($id);

        alert()->success('Hapus Data UserPostDetail', 'Sukses')->autoclose(10000);

        return redirect('user-post-detail');
    }
}

resources/views/user/user-page/index.blade.php
@extends('layouts.main.app')

@section('title')
User Page
@endsection

@section('content')
<div class="panel-header bg-primary-gradient">
    <div class="page-inner py-5">
        <div class="d-flex align-items-left align-items-md-center flex-column flex-md-row">
            <div>
                <h2 class="text-white pb-2 fw-bold">@yield('title')</h2>
                <h5 class="text-white op-7 mb-3"></h5>
            </div>
        </div>
    </div>
</div>
<div class="page-inner mt--5">
    <div class="container-fluid">
        <!-- CONTENT -->
        <a href="{{ route('user-page.create') }}" class="btn btn-success btn-sm" title="Tambah User Page">
            <i class="fa fa-plus" aria-hidden="true"></i> Tambah Data
        </a>

        <br />
        <br />
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">Filter Data</h3>


            </div>
            <div class="card-body">
                <div class="row">
                    <div class="col-md-12">
                        <form method="GET" action="{{ route('user-page.index') }}" accept-charset="UTF-8" role="search">
                            <div class="input-group">
                                <input type="text" class="form-control" name="search" placeholder="Cari..."
                                    value="{{ request('search') }}">
                                <span class="input-group-append">
                                    <button class="btn btn-secondary" type="submit">
                                        <i class="fa fa-search"></i>
                                    </button>
                                </span>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">@yield('title')</h3>

            </div>
            <!-- /.card-header -->

            <div class="card-body">

                <div class="table-responsive">
                    <table id="userpage" class="table table-bordered table-hover">
                        <thead>
                            <tr>
                                <th>#</th>
                                <th>Title</th>
                                <th>Menu</th>
                                <th>Foto</th>
                                <th>Thumbnail</th>
                                <th>Detail</th>
                                <th>Aksi</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach($userpage as $item)
                            <tr>
                                <td>{{ $loop->iteration }}</td>
                                <td>{{ $item->title }}</td>
                                <td>{{ $item->menu_id }}</td>
                                <td>
                                    <center>
                                        <img id='img-upload' style="width: 40%"
                                            src="{{ asset('img/pageuser/'.$item->foto) }}" /> <br><br>
                                    </center>
                                </td>
                                <td>
                                    <center>
                                        <img id='img-upload' style="width: 40%"
                                            src="{{ asset('img/pageuser/'.$item->thumbnail) }}" /> <br><br>
                                    </center>
                                </td>
                                <td>{{ $item->detail }}</td>
                                <td>
                                    <div class="btn-group" role="group">
                                        <a href="{{ route('user-page.show', $item->id) }}"
                                            title="Lihat User Page"><button class="btn btn-info btn-sm"><i
                                                    class="fas fa-eye" aria-hidden="true"></i>
                                            </button></a>
                                        <a href="{{ route('user-page.edit', $item->id) }}"
                                            title="Edit User Page"><button class="btn btn-primary btn-sm"><i
                                                    class="fas fa-edit" aria-hidden="true"></i>
                                            </button></a>

                                        <form method="POST" action="{{ route('user-page.destroy', $item->id) }}"
                                            accept-charset="UTF-8" style="display:inline">
                                            {{ method_field('DELETE') }}
                                            {{ csrf_field() }}
                                            <button type="submit" class="btn btn-danger btn-sm delete-confirm"
                                                title="Hapus User Page"><i class="fas fa-trash" aria-hidden="true"></i>
                                            </button>
                                        </form>
                                    </div>
                                </td>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div><!-- /.card-body -->

            <div class="card-footer">

            </div><!-- /.card-footer -->


        </div><!-- /.card -->
    </div>
    <!-- /.container-fluid -->
</div>
@endsection

@section('css')
<!-- DataTables -->
<link rel="stylesheet" href="{{ asset('vendor/datatables-bs4/css/dataTables.bootstrap4.min.css') }}">
<link rel="stylesheet" href="{{ asset('vendor/datatables-responsive/css/responsive.bootstrap4.min.css') }}">
<link rel="stylesheet" href="{{ asset('vendor/datatables-buttons/css/buttons.bootstrap4.min.css') }}">

@endsection

@section('js')
<!-- DataTables  & Plugins -->
<script src="{{ asset('vendor/datatables/jquery.dataTables.min.js') }}"></script>
<script src="{{ asset('vendor/datatables-bs4/js/dataTables.bootstrap4.min.js') }}"></script>
<script src="{{ asset('vendor/datatables-responsive/js/dataTables.responsive.min.js') }}"></script>
<script src="{{ asset('vendor/datatables-responsive/js/responsive.bootstrap4.min.js') }}"></script>
<script src="{{ asset('vendor/datatables-buttons/js/dataTables.buttons.min.js') }}"></script>
<script src="{{ asset('vendor/datatables-buttons/js/buttons.bootstrap4.min.js') }}"></script>
<script src="{{ asset('vendor/jszip/jszip.min.js') }}"></script>
<script src="{{ asset('vendor/pdfmake/pdfmake.min.js') }}"></script>
<script src="{{ asset('vendor/pdfmake/vfs_fonts.js') }}"></script>
<script src="{{ asset('vendor/datatables-buttons/js/buttons.html5.min.js') }}"></script>
<script src="{{ asset('vendor/datatables-buttons/js/buttons.print.min.js') }}"></script>
<script src="{{ asset('vendor/datatables-buttons/js/buttons.colVis.min.js') }}"></script>
<!-- Page specific script -->

<script>
    $(function () {
    if ( $.fn.dataTable.isDataTable( '#userpage' ) ) {
            table = $('#userpage').DataTable();
        }
        else {
            table = $("#userpage").DataTable({
                        responsive: true,
                        lengthChange: false,
                        autoWidth: false,
                        searching: false,
                        paging: true,
                        ordering: false
            }).buttons().container().appendTo('#userpage_wrapper .col-md-6:eq(0)');

        }
    });
    $('.delete-confirm').on('click', function (event) {
        var form =  $(this).closest("form");
        var name = $(this).data("name");
        event.preventDefault();
        swal({
            title: `Apakah Anda Yakin Untuk Menghapus Data Ini ?`,
            text: "Jika dihapus data tidak akan ditampilkan lagi",
            icon: "warning",
            buttons: ["Tidak", "Ya!"],
            dangerMode: true,
        })
        .then((willDelete) => {
        if (willDelete) {
            form.submit();
        }
        });
    });
</script>

@endsection

resources/views/user/user-page/show.blade.php
@extends('layouts.main.app')
@section('title')
Lihat User Page #{{ $userpage->id }}
@endsection

@section('content')
<div class="page-inner">
    <div class="container-fluid">
        <!-- CONTENT -->
        <div class="card card-default">
            <div class="card-header">
                <h3 class="card-title">@yield('title')</h3>

            </div>
            <!-- /.card-header -->
            <div class="card-body">
                <a href="{{ route('user-page.index') }}" title="Kembali"><button class="btn btn-warning btn-sm"><i
                            class="fas fa-arrow-left" aria-hidden="true"></i>
                        Kembali</button></a>

                <a href="{{ route('user-page.edit', $userpage->id) }}" title="Edit User Page"><button
                        class="btn btn-primary btn-sm"><i class="fas fa-edit" aria-hidden="true">&nbsp; Edit</i>
                    </button></a>

                <form method="POST" action="{{ route('user-page.destroy', $userpage->id) }}" accept-charset="UTF-8"
                    style="display:inline">
                    {{ method_field('DELETE') }}
                    {{ csrf_field() }}
                    <button type="submit" class="btn btn-danger btn-sm delete-confirm" title="Delete User Page"><i
                            class="fas fa-trash" aria-hidden="true"></i>
                        &nbsp; Hapus</button>
                </form>
                <br />
                <br />

                <div class="table-responsive">
                    <table class="table table-striped">
                        <tbody>
                            <tr>
                                <th>ID</th>
                                <td>{{ $userpage->id }}</td>
                            </tr>
                            <tr>
                                <th> Title </th>
                                <td> {{ $userpage->title }} </td>
                            </tr>
                            <tr>
                                <th> Detail </th>
                                <td> {{ $userpage->detail }} </td>
                            </tr>
                            <tr>
                                <th> Menu </th>
                                <td> {{ $userpage->menu_id }} </td>
                            </tr>
                            <tr>
                                <th> Foto </th>
                                <td>
                                    <center>
                                        <img id='img-upload' style="width: 40%"
                                            src="{{ asset('img/pageuser/'.$userpage->foto) }}" /> <br><br>
                                    </center>
                                </td>
                            </tr>
                            <tr>
                                <th> Thumbnail </th>
                                <td>
                                    <center>
                                        <img id='img-upload' style="width: 40%"
                                            src="{{ asset('img/pageuser/'.$userpage->thumbnail) }}" /> <br><br>
                                    </center>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </div>



            </div><!-- /.card-body -->
        </div><!-- /.card -->
    </div>
    <!-- /.container-fluid -->
</div>
@endsection

@section('css')

@endsection

@section('js')
<script>
    $('.delete-confirm').on('click', function (event) {
          var form =  $(this).closest("form");
          var name = $(this).data("name");
          event.preventDefault();
          swal({
              title: `Apakah Anda Yakin Untuk Menghapus Data Ini ?`,
              text: "Jika dihapus data tidak akan ditampilkan lagi",
              icon: "warning",
              buttons: ["Tidak", "Ya!"],
              dangerMode: true,
          })
          .then((willDelete) => {
            if (willDelete) {
              form.submit();
            }
          });
      });
</script>
@endsection